import Head from 'next/head'
import { useSession } from '@supabase/auth-helpers-react'
import styles from '../styles/Home.module.css'
import Account from '../components/Account'
import Header from '../components/Header'
import Auth from '../components/Auth'
import { ThemeProvider, CssBaseline } from '@mui/material'
import { useAppContext } from '../context/AppContext'

export default function AccountPage() {
  const session = useSession()
  const { theme } = useAppContext()

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />

      <div className={styles.container}>
        <Head>
          <title>PokeTracker - Account</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/pokeball-dark.ico" media="(prefers-color-scheme: dark)" />
          <link rel="icon" href="/pokeball-light.ico" media="(prefers-color-scheme: light)" />
          <link rel="icon" href="/pokeball.ico" media="(prefers-color-scheme: no-preference)" />
        </Head>

        <Header />

        <main className={styles.main}>
          <div style={{ padding: '50px 0 100px 0' }}>
            {!session ? (
              <Auth />
            ) : (
              <Account session={session} />
            )}
          </div>
        </main>
      </div>
    </ThemeProvider>
  )
}